name: fitness_app
version: 1.0.0+1
description: Fitness App for Android and iOS
homepage: https://github.com/Vadime/FitnessApp
repository: https://github.com/Vadime/FitnessApp
issue_tracker: https://github.com/Vadime/FitnessApp/issues
documentation: https://github.com/Vadime/FitnessApp/docs

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.12
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4

  cloud_functions: ^4.3.4
  firebase_storage: ^11.2.5
  shared_preferences: ^2.2.0
  file_picker: ^5.3.3
  flutter_native_splash: ^2.3.1
  firebase_crashlytics: ^3.3.4

  onboarding: 
    git: 
      url: https://github.com/Vadime/flutter_onboarding.git
      ref: development

  firebase_analytics: ^10.4.4
  fl_chart: ^0.63.0
  
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.4.1
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3
  flutter_launcher_icons: ^0.13.1

  flutter_rename_app:
    git:
      url: https://github.com/Vadime/flutter_rename_app.git
      ref: master
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

# dependency_overrides:

environment:
  sdk: '>=3.0.5 <4.0.0'

# executables:

platforms: [android, ios]

publish_to: 'none' 

# funding: []

# false_secrets: 

# screenshots:

topics: [fitness,workout,health,sport,app]

flutter:

  uses-material-design: true

  assets:
    # - res/images/dark_background.jpg
    - res/logo/foreground.png

  fonts:
    - family: Varela Round
      fonts:
        - asset: res/fonts/Varela_Round/VarelaRound-Regular.ttf

