name: fitness_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  formz: ^0.6.0
  uuid: ^3.0.7

  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.12
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  onboarding: 
    path: packages/onboarding
  cloud_functions: ^4.3.4
  firebase_storage: ^11.2.5
  shared_preferences: ^2.2.0
  file_picker: ^5.3.3
  flutter_native_splash: ^2.3.1
  firebase_crashlytics: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3
  flutter_launcher_icons: ^0.13.1

  flutter_rename_app:
    path: packages/flutter_rename_app

flutter:

  uses-material-design: true

  assets:
    - res/images/dark_background.jpg
    - res/logo/foreground.png
    - res/config/onboarding.json
    - res/config/general.json

  fonts:
    - family: Varela Round
      fonts:
        - asset: res/fonts/Varela_Round/VarelaRound-Regular.ttf

