name: fitnessapp
version: 0.0.7+3
description: Fitness App for Android and iOS
homepage: https://github.com/Vadime/FitnessApp
repository: https://github.com/Vadime/FitnessApp
issue_tracker: https://github.com/Vadime/FitnessApp/issues
documentation: https://github.com/Vadime/FitnessApp/docs

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  cloud_functions: ^4.3.4
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4
  firebase_messaging: ^14.6.7

  flutter_native_splash: ^2.3.1

  widgets:
    path: ./packages/widgets

  provider: ^6.0.5
  fl_chart: ^0.63.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  intl_translation: ^0.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: master

# dependency_overrides:
environment:
  sdk: '>=3.0.5 <4.0.0'

# executables:
# platforms: [android, ios]
publish_to: 'none'

# funding: []
# false_secrets: 
# screenshots:
# topics: [fitness,workout,health,sport,app]
flutter:
  generate: true
  uses-material-design: true

  assets:
    - res/logo/foreground.png

  fonts:
    - family: Varela Round
      fonts:
        - asset: res/fonts/VarelaRound-Regular.ttf

# dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "res/logo/foreground.png"

  android: true
  adaptive_icon_background: "#EEEEEE"
  adaptive_icon_foreground: "res/logo/foreground.png"
  min_sdk_android: 23

  ios: true
  remove_alpha_ios: true
  background_color_ios: "#EEEEEE"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#EEEEEE"
  image: res/logo/foreground.png
  
flutter_intl:
  enabled: true
